[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Upload settings
monitor_speed = 115200
upload_speed = 921600

; Libraries
lib_deps = 
    bblanchon/ArduinoJson@^6.21.3
    bodmer/TFT_eSPI@^2.5.23

; Build flags
build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=240
    -DTFT_MOSI=23
    -DTFT_SCLK=18
    -DTFT_CS=5
    -DTFT_DC=16
    -DTFT_RST=17
    -DTFT_BL=4
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DLOAD_FONT6=1
    -DLOAD_FONT7=1
    -DLOAD_FONT8=1
    -DLOAD_GFXFF=1
    -DSMOOTH_FONT=1
    -DSPI_FREQUENCY=40000000

