[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Upload settings
monitor_speed = 115200
upload_speed = 115200

; Libraries
lib_deps = 
    bblanchon/ArduinoJson@^6.21.3
    arduino-libraries/Ethernet@^2.0.2

; Build flags
build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DSPI_FREQUENCY=40000000

